title:            Ajay G
subtitle:         
description:      Ajay G's Personal Website.
keywords:         Planning, Control, Bio-inspired, Underactuated Robots, Real-Time, Sotware-development.
language:         "en"
baseurl:          "" 
url:              "http://ajaygunalan.github.io/"
permalink:        /blog/:categories/:title
cover:            /assets/machu_lacta.jpg
disqus_shortname: "https-ajaygunalan-github-io"

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    input: GFM
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        # Use existing pygments syntax highlighting css
        css_class: 'highlight'
include: ['_pages']
exclude: [vendor]
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
github: [metadata]
future: true