title:            Ajay Gunalan
subtitle:         
description:      Ajay Gunalan's Personal Website.
keywords:         Deisgn, optimisation, systems and controls, MEMS, optics, and electronics.
language:         "en"
baseurl:          "" 
url:              "http://ajaygunalan.github.io/"
permalink:        /blog/:categories/:title
cover:            /assets/machu_lacta.jpg
disqus_shortname: "https-ajaygunalan-github-io"
plugins:
  - jekyll-last-modified-at

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%d-%b-%y'

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    input: GFM
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        # Use existing pygments syntax highlighting css
        css_class: 'highlight'
include: ['_pages']
exclude: [vendor]
plugins_dir:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
github: [metadata]
future: true
