baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Ajay Gunalan
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 1 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 5

params:
    #description: "I am a Professor of Philology at the Institute of Romance Philology in Regensburg, Germany. My research focuses mostly on Portuguese irregular verbs.
#consequat."
    # author: Ajay Gunalan
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Ajay Gunalan
          subtitle: "
          I'm a Ph.D. student at the [Italian Institute of Technology](https://iit.it/). My current research focuses on the development of novel laser technologies for micro-surgical robots. 
          My previous experiences include developing [medical device](https://ajaygunalan.github.io/newWebsite/projects/pre_phd/sid/), [humanoid](), [legged robot](), and [tele-robotics](). 
          
          <br><br> 
          My vision is to make healthcare affordable by merging medicine and engineering. In this process, I love working with a diverse team to develop transformative tech and solve new challenges each day.
          
          <br> <br> 
          I firmly believe that when Robots and AI automate all jobs and work. It will be a massive blessing for humanity as we need not work ever; instead, we can do whatever we love! **Isn't that lovely?** 
          
          "    
          imageUrl: "picture.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Ajay Gunalan
          buttons:
            - name: Books
              url: books/
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
            - name: Data
              url: data/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: Email
          url: mailto:ajay.gunalan@pm.me
        - name: CV
          url: ajayg_cv.pdf
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=en&user=mYcXHpgAAAAJ&view_op=list_works&sortby=pubdate
        #- name: Location
          #url: location/
        #- name: Office Hours
          #url: officehours/
        - name: GitHub
          url: https://github.com/ajaygunalan/
        #- name: YouTube
          #url: https://www.youtube.com/@alexandermccallsmithoffici9000
        #- name: Twitter
          #url: https://twitter.com/McCallSmith

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Moritz-Maria von Igelfeld"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
