baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Ajay Gunalan
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: projects/
          weight: 1 
        - name: Tech Blog
          url: tech_blogs/
          weight: 2
        - name: CV
          url: ajayg_cv.pdf
          weight: 3
        - name: Life Blog
          url: life_blogs/
          weight: 4

params:
    #description: ""
    # author: Ajay Gunalan
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Ajay Gunalan
          subtitle: "
          > *What I cannot create, I do not understand — Richard Feynman.*

          <br><br> 
          I'm a postdoctoral fellow in the [<u>PULSE Lab</u>](https://pulselab.jhu.edu/) at Johns Hopkins University. I graduated with a Ph.d. in medical robotics at  [<u>Italian Institute of Technology</u>](https://iit.it/), where I focused on the development of novel laser technologies for micro-surgical robots. 
          My previous experiences include working on [<u>tele-robotics</u>](https://ajaygunalan.com/projects/telerobo/), [<u>legged robotics</u>](https://ajaygunalan.com/projects/iisc/), [<u>humanoid</u>](https://ajaygunalan.com/projects/asimov/), and [<u>medical device</u>](https://ajaygunalan.com/projects/sid/). 
          
          <br><br> 
          My vision is to improve healthcare by developing cutting-edge technology through the fusion of multiple disciplines. In this process, I enjoy working with a diverse team to solve new challenges.
          
          <br> <br> 
          I firmly believe that when Robots and AI automate all jobs and work. It will be a massive blessing for humanity as we need not work ever; instead, we can do whatever we love! **Isn't that lovely?** 
          
          "    
          imageUrl: "picture.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Ajay Gunalan
          buttons:
            - name: Pojects
              url: projects/
            - name: Tech Blog
              url: tech_blogs/
            - name: CV
              url: ajayg_cv.pdf
            - name: Life Blog
              url: life_blogs/
    socialIcons:
        - name: Email
          url: mailto:ajay.gunalan@pm.me
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=en&user=mYcXHpgAAAAJ&view_op=list_works&sortby=pubdate
        #- name: Location
          #url: location/
        #- name: Office Hours
          #url: officehours/
        - name: GitHub
          url: https://github.com/ajaygunalan/
        #- name: YouTube
          #url: https://www.youtube.com/@alexandermccallsmithoffici9000
        #- name: Twitter
          #url: https://twitter.com/McCallSmith

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Ajay Gunalan"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
