baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Ajay Gunalan
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: projects/
          weight: 1 
        - name: Blog
          url: blogs/
          weight: 2
        - name: CV
          url: ajayg_cv.pdf
          weight: 3

params:
    #description: "I am a Professor of Philology at the Institute of Romance Philology in Regensburg, Germany. My research focuses mostly on Portuguese irregular verbs.
#consequat."
    # author: Ajay Gunalan
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Ajay Gunalan
          subtitle: "
          > *What I cannot create, I do not understand — Richard Feynman.*

          <br><br> 
          I'm a Ph.D. student at the [<u>Italian Institute of Technology</u>](https://iit.it/). My current research focuses on the development of novel laser technologies for micro-surgical robots. 
          My previous experiences include developing [<u>medical device</u>](https://ajaygunalan.github.io/projects/sid/), [<u>humanoid</u>](https://ajaygunalan.github.io//projects/asimov/), [<u>legged robot</u>](https://ajaygunalan.github.io/projects/iisc/), and [<u>tele-robotics</u>](https://ajaygunalan.github.io/projects/telerobo/). 
          
          <br><br> 
          My vision is to make healthcare affordable by merging medicine and engineering. In this process, I love working with a diverse team to develop transformative tech and solve new challenges each day.
          
          <br> <br> 
          I firmly believe that when Robots and AI automate all jobs and work. It will be a massive blessing for humanity as we need not work ever; instead, we can do whatever we love! **Isn't that lovely?** 
          
          "    
          imageUrl: "picture.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Ajay Gunalan
          buttons:
            - name: Pojects
              url: projects/
            - name: Blog
              url: blogs/
            - name: CV
              url: ajayg_cv.pdf
    socialIcons:
        - name: Email
          url: mailto:ajay.gunalan@pm.me
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=en&user=mYcXHpgAAAAJ&view_op=list_works&sortby=pubdate
        #- name: Location
          #url: location/
        #- name: Office Hours
          #url: officehours/
        - name: GitHub
          url: https://github.com/ajaygunalan/
        #- name: YouTube
          #url: https://www.youtube.com/@alexandermccallsmithoffici9000
        #- name: Twitter
          #url: https://twitter.com/McCallSmith

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Ajay Gunalan"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
